"""Replace models with User, ValidToken, SurveyResponse

Revision ID: 40cc53153680
Revises: 
Create Date: 2025-04-19 08:14:56.938066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40cc53153680'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('valid_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('valid_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_valid_tokens_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_valid_tokens_used'), ['used'], unique=False)

    op.create_table('survey_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genero', sa.String(length=50), nullable=True),
    sa.Column('localidad', sa.String(length=100), nullable=True),
    sa.Column('edad', sa.String(length=50), nullable=True),
    sa.Column('intendente', sa.String(length=150), nullable=True),
    sa.Column('balotaje', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=150), nullable=True),
    sa.Column('partido_vs_persona', sa.String(length=150), nullable=True),
    sa.Column('percepcion_mario', sa.String(length=50), nullable=True),
    sa.Column('percepcion_daniel', sa.String(length=50), nullable=True),
    sa.Column('problemas', sa.String(length=150), nullable=True),
    sa.Column('auditoria', sa.String(length=250), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('submission_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['valid_tokens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_responses')
    with op.batch_alter_table('valid_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_valid_tokens_used'))
        batch_op.drop_index(batch_op.f('ix_valid_tokens_token'))

    op.drop_table('valid_tokens')
    op.drop_table('users')
    # ### end Alembic commands ###
